### ISSUE TITLE
How to detect Java_Home is correct set?

### ISSUE THREAD

**Issue by bnuzhouwei** [abstracta/jmeter-dotnet-dsl#13]
I test it [jmeter-dotnet-dsl](https://github.com/abstracta/jmeter-dotnet-dsl) on local development success, but deploy on server failed, I have set the JAVA_HOME，any other should be set?

**Comment by rabelenda** [comment]
Hello, can you provide more details on how it fails? Maybe some log output or some screenshot?

**Comment by bnuzhouwei** [comment]
I have found that if start with the exe file, it's all right,
but if it start with IIS, it will got:

```bash
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
```

That is the JmeterDSL can not work when hosted in IIS.

**Comment by rabelenda** [comment]
The exception is a .Net exception. I don't know of any `path1` parameter related to jmeter dsl itself. 

The issue seems to be related on how you run jmeter dsl locally and in IIS, maybe something related on how you package the performance test and distribute it? or maybe something related with IIS package resolution? 

Maybe if you provide more details on how your project looks, what steps you took to run it locally, and what steps you took to upload it and try to run it in IIS, someone could provide some hint on how to solve your issue.

Regards

**Comment by rabelenda** [comment]
I am closing this since we didn't get any further info and the issue seems not to be directly related to JMeter DSL itself. Feel free to reopen it if you feel the need.
